# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorLoggingApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='fileName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
