# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorLoggingApi', '0002_eventdata_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='videoFile',
        ),
    ]
